timezone: Australia/Sydney
designations:
  light_rail:
    prefix: LR
  rapid:
    prefix: R
route:
  real-time:
    - id: ACTO001
      url: https://files.transport.act.gov.au/feeds/lightrail.pb
    - id: NIS
      url: https://files.transport.act.gov.au/feeds/lightrail.pb
    - id: X1
      url: https://files.transport.act.gov.au/feeds/lightrail.pb
    - id: X2
      url: https://files.transport.act.gov.au/feeds/lightrail.pb
    - id: X3
      url: https://files.transport.act.gov.au/feeds/lightrail.pb
    - id: X4
      url: https://files.transport.act.gov.au/feeds/lightrail.pb
  special-designations:
    - code: 1
      designation: light_rail
    - code: 2
      designation: rapid
    - code: 3
      designation: rapid
    - code: 4
      designation: rapid
    - code: 5
      designation: rapid
    - code: 6
      designation: rapid
    - code: 7
      designation: rapid
    - code: 8
      designation: rapid
    - code: 9
      designation: rapid
    - code: 10
      designation: rapid
  colors:
    - code: 1
      color: DA1F3A
      onColor: light
    - code: 2
      color: ebb9d5
      onColor: dark
    - code: 3
      color: f9da5c
      onColor: dark
    - code: 4
      color: 479ecd
      onColor: light
    - code: 5
      color: d14a9b
      onColor: light
    - code: 6
      color: 83bf58
      onColor: dark
    - code: 7
      color: e0803d
      onColor: light
    - code: 8
      color: "282724"
      onColor: light
    - code: 9
      color: "929c9c"
      onColor: dark
    - code: 10
      color: "a8332f"
      onColor: light
  modifications:
    NIS:
      hidden: true
      search-weight: 0.2
    X1:
      hidden: true
    X2:
      hidden: true
    X3:
      hidden: true
    X4:
      hidden: true
    1:
      search-weight: 1.7
    2:
      search-weight: 1.7
    3:
      search-weight: 1.7
    4:
      search-weight: 1.7
    5:
      search-weight: 1.7
    6:
      search-weight: 1.7
    7:
      search-weight: 1.7
    8:
      search-weight: 1.7
    9:
      search-weight: 1.7
    10:
      search-weight: 1.7
stops:
  modifications:
    city-interchange:
      show-on-zoom-out: true
      show-on-zoom-in: false
      show-children: true
    belconnen-interchange:
      show-on-zoom-out: true
      show-on-zoom-in: false
      show-children: true
    tuggeranong-interchange:
      show-on-zoom-out: true
      show-on-zoom-in: false
      show-children: true
    woden-interchange:
      show-on-zoom-out: true
      show-on-zoom-in: false
      show-children: true
    dickson-interchange:
      show-on-zoom-out: true
      show-on-zoom-in: false
      show-children: true
    gungahlin-interchange:
      show-on-zoom-out: true
      show-on-zoom-in: false
      show-children: true
    cohen-st-interchange:
      show-on-zoom-out: true
      show-on-zoom-in: false
      show-children: true