timezone: Australia/Sydney
designations:
  light_rail:
    prefix: LR
  rapid:
    prefix: R
route:
  special-designations:
    - code: 1
      designation: light_rail
    - code: 2
      designation: rapid
    - code: 3
      designation: rapid
    - code: 4
      designation: rapid
    - code: 5
      designation: rapid
    - code: 6
      designation: rapid
    - code: 7
      designation: rapid
    - code: 8
      designation: rapid
    - code: 9
      designation: rapid
    - code: 10
      designation: rapid
  colors:
    - code: 1
      color: DA1F3A
      onColor: light
    - code: 2
      color: ebb9d5
      onColor: dark
    - code: 3
      color: f9da5c
      onColor: dark
    - code: 4
      color: 479ecd
      onColor: light
    - code: 5
      color: d14a9b
      onColor: light
    - code: 6
      color: 83bf58
      onColor: dark
    - code: 7
      color: e0803d
      onColor: light
    - code: 8
      color: "282724"
      onColor: light
    - code: 9
      color: "929c9c"
      onColor: dark
    - code: 10
      color: "a8332f"
      onColor: light
    - code: F1
      color: "dc177a"
      onColor: light
  modifications:
    ACTO001:
      has-realtime: true
    NIS:
      hidden: true
      search-weight: 0.2
    X1:
      hidden: true
      has-realtime: true
    X2:
      hidden: true
      has-realtime: true
    X3:
      hidden: true
    X4:
      hidden: true
    1-10657:
      search-weight: 1.7
    2-10657:
      search-weight: 1.7
    3-10657:
      search-weight: 1.7
    4-10657:
      search-weight: 1.7
    5-10657:
      search-weight: 1.7
      name: Lanyon to City ANU via Erindale & Woden
    6-10657:
      search-weight: 1.7
    7-10657:
      search-weight: 1.7
    8-10657:
      search-weight: 1.7
    9-10657:
      search-weight: 1.7
    10-10657:
      search-weight: 1.7
    41-10657:
      name: Fraser to Belconnen via Charnwood
    47-10657:
      name: Belconnen to Denman Prospect via Whitlam
    80-10657:
      name: Lanyon Marketplace to Tuggeranong via Banks
    81-10657:
      name: Lanyon Marketplace to Tuggeranong via Gordon
    floriade_2025_1:
      show-on-browse: true
      approximate-timings: true
      event-route: true
      description: |
        Floriade, Australia's Biggest Celebration of Spring, returns to Commonwealth Park.

        Catch the free **Floriade Shuttle Bus** from the city or National Triangle direct to the Floriade gates.
      more-link: https://events.canberra.com.au/whats-on/66399c89e45a397e21dffe32/floriade-2025
    floriade_2025_2:
      show-on-browse: false
      approximate-timings: true
      event-route: true
      description: |
        Floriade, Australia's Biggest Celebration of Spring, returns to Commonwealth Park.

        The free **Floriade Weekend Express** will leave from Belconnen Interchange at Westfield, stop at Emu Bank and then travel direct to Regatta Point to drop passengers at the Floriade gates. Weekends and NightFest only.
      more-link: https://events.canberra.com.au/whats-on/66399c89e45a397e21dffe32/floriade-2025
    floriade_2025_3:
      show-on-browse: false
      approximate-timings: true
      event-route: true
      description: |
        Floriade, Australia's Biggest Celebration of Spring, returns to Commonwealth Park.

        The free **Floriade Weekend Express** will leave from Tuggeranong Interchange and Woden Interchange and travel direct to Regatta Point to drop passengers at the Floriade gates. Weekends and NightFest only.
      more-link: https://events.canberra.com.au/whats-on/66399c89e45a397e21dffe32/floriade-2025
stops:
  modifications:
    "959":
      name: Cohen St Interchange (Stop)
    "DKN":
      name: Dickson Interchange (Stop)
      has-realtime: true
    "GGN":
      has-realtime: true
    "MCK":
      has-realtime: true
    "MPN":
      has-realtime: true
    "NLR":
      has-realtime: true
    "WSN":
      has-realtime: true
    "SFD":
      has-realtime: true
    "EPC":
      has-realtime: true
    "PLP":
      has-realtime: true
    "SWN":
      has-realtime: true
    "MCR":
      has-realtime: true
    "IPA":
      has-realtime: true
    "ELA":
      has-realtime: true
    "ALG":
      has-realtime: true
    city-interchange:
      show-on-zoom-out: true
      show-on-zoom-in: false
      show-children: true
      has-realtime: true
    belconnen-interchange:
      show-on-zoom-out: true
      show-on-zoom-in: false
      show-children: true
    tuggeranong-interchange:
      show-on-zoom-out: true
      show-on-zoom-in: false
      show-children: true
    woden-interchange:
      show-on-zoom-out: true
      show-on-zoom-in: false
      show-children: true
    dickson-interchange:
      show-on-zoom-out: true
      show-on-zoom-in: false
      show-children: true
    gungahlin-interchange:
      show-on-zoom-out: true
      show-on-zoom-in: false
      show-children: true
      has-realtime: true
    cohen-st-interchange:
      show-on-zoom-out: true
      show-on-zoom-in: false
      show-children: true
    "8100":
      show-on-zoom-in: false
      has-realtime: true
    "8101":
      show-on-zoom-in: false
      has-realtime: true
    "8104":
      show-on-zoom-in: false
      has-realtime: true
    "8105":
      show-on-zoom-in: false
      has-realtime: true
    "8106":
      show-on-zoom-in: false
      has-realtime: true
    "8107":
      show-on-zoom-in: false
      has-realtime: true
    "8108":
      show-on-zoom-in: false
      has-realtime: true
    "8109":
      show-on-zoom-in: false
      has-realtime: true
    "8110":
      show-on-zoom-in: false
      has-realtime: true
    "8111":
      show-on-zoom-in: false
      has-realtime: true
    "8112":
      show-on-zoom-in: false
      has-realtime: true
    "8113":
      show-on-zoom-in: false
      has-realtime: true
    "8114":
      show-on-zoom-in: false
      has-realtime: true
    "8115":
      show-on-zoom-in: false
      has-realtime: true
    "8116":
      show-on-zoom-in: false
      has-realtime: true
    "8117":
      show-on-zoom-in: false
      has-realtime: true
    "8118":
      show-on-zoom-in: false
      has-realtime: true
    "8119":
      show-on-zoom-in: false
      has-realtime: true
    "8120":
      show-on-zoom-in: false
      has-realtime: true
    "8121":
      show-on-zoom-in: false
      has-realtime: true
    "8122":
      show-on-zoom-in: false
      has-realtime: true
    "8123":
      show-on-zoom-in: false
      has-realtime: true
    "8124":
      show-on-zoom-in: false
      has-realtime: true
    "8125":
      show-on-zoom-in: false
      has-realtime: true
    "8126":
      show-on-zoom-in: false
      has-realtime: true
    "8127":
      show-on-zoom-in: false
      has-realtime: true
    "8128":
      show-on-zoom-in: false
      has-realtime: true
    "8129":
      show-on-zoom-in: false
      has-realtime: true
    "1801":
      show-on-zoom-in: false
    "7011":
      show-on-zoom-in: false
      name: Gungahlin Place Plt 3 Departures
    "7012":
      show-on-zoom-in: false
      name: Gungahlin Place Plt 4 Departures
    "7016":
      show-on-zoom-in: false
    "1721":
      show-on-zoom-in: false
    "3402":
      show-on-zoom-in: false
      name: City Interchange Plt 11 Departures
    "5517":
      name: Belconnen Interchange Arrivals South
    "5518":
      name: Belconnen Interchange Arrivals North
    "1708":
      name: City Interchange Plt 7
