# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: format.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'format.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66ormat.proto\x12\x05proto\")\n\x0cStopEndpoint\x12\x19\n\x04stop\x18\x01 \x03(\x0b\x32\x0b.proto.Stop\",\n\rRouteEndpoint\x12\x1b\n\x05route\x18\x02 \x03(\x0b\x32\x0c.proto.Route\"t\n\x04Stop\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12!\n\x08location\x18\x03 \x02(\x0b\x32\x0f.proto.Location\x12/\n\raccessibility\x18\x04 \x02(\x0b\x32\x18.proto.StopAccessibility\"=\n\x05Route\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04\x63ode\x18\x02 \x02(\t\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\x0c\n\x04type\x18\x04 \x02(\t\"K\n\x11StopAccessibility\x12\x36\n\nwheelchair\x18\x01 \x02(\x0e\x32\".proto.WheelchairStopAccessibility\"$\n\x08Location\x12\x0b\n\x03lat\x18\x01 \x02(\x01\x12\x0b\n\x03lng\x18\x02 \x02(\x01*\x98\x01\n\x1bWheelchairStopAccessibility\x12&\n\"WHEELCHAIR_STOP_ACCESSIBILITY_NONE\x10\x00\x12)\n%WHEELCHAIR_STOP_ACCESSIBILITY_PARTIAL\x10\x01\x12&\n\"WHEELCHAIR_STOP_ACCESSIBILITY_FULL\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'format_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WHEELCHAIRSTOPACCESSIBILITY']._serialized_start=409
  _globals['_WHEELCHAIRSTOPACCESSIBILITY']._serialized_end=561
  _globals['_STOPENDPOINT']._serialized_start=23
  _globals['_STOPENDPOINT']._serialized_end=64
  _globals['_ROUTEENDPOINT']._serialized_start=66
  _globals['_ROUTEENDPOINT']._serialized_end=110
  _globals['_STOP']._serialized_start=112
  _globals['_STOP']._serialized_end=228
  _globals['_ROUTE']._serialized_start=230
  _globals['_ROUTE']._serialized_end=291
  _globals['_STOPACCESSIBILITY']._serialized_start=293
  _globals['_STOPACCESSIBILITY']._serialized_end=368
  _globals['_LOCATION']._serialized_start=370
  _globals['_LOCATION']._serialized_end=406
# @@protoc_insertion_point(module_scope)
