name: Generate for Canberra

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10.13'
            cache: 'pip'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r script/requirements.txt
        - name: Download data
          run: |
            wget -q https://www.transport.act.gov.au/googletransit/google_transit.zip
            wget -q https://www.transport.act.gov.au/googletransit/google_transit_lr.zip
            
            mkdir canberra
            unzip google_transit.zip -d canberra/normal
            unzip google_transit_lr.zip -d canberra/lr
        - name: Run script
          run: |
            python script/script.py -c config-canberra.yml -i canberra/normal -i canberra/lr -o build/canberra/v1
        - name: Generate content
          run: |
            ./render-content.sh
            cp content/content{.json,.json.sha,.pb,.pb.sha} build/canberra/v1
        - name: Setup AWS CLI
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ vars.AWS_REGION }}
        - run: aws s3 sync build s3://${{ vars.AWS_BUCKET }} --delete
                