name: TEST Generate for Canberra

on:
  pull_request:
    branches: 
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.13'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api-generator/requirements.txt
      - name: Download data
        run: |
          wget -q https://www.transport.act.gov.au/googletransit/google_transit.zip
          wget -q https://www.transport.act.gov.au/googletransit/google_transit_lr.zip
          
          mkdir canberra
          unzip google_transit.zip -d canberra/normal
          unzip google_transit_lr.zip -d canberra/lr
      - name: Run script
        run: |
          python api-generator/script.py generate -c config-canberra.yml -i canberra/normal -i canberra/lr -i event-service -g stop-manager/groups.yml -o build/canberra/v1
      - name: Calculate diff
        run: |
          mkdir out
          docker run \ 
            -v "./build:/build"
            -v "./out:/out"
            --rm -t ghcr.io/sinatra-transport/s3-sync-utility:0.1.1 \ 
            build -i /build -o /out/index.pb
      - name: Print changes
        run: |
          docker run \
            -e "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -e "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -e "AWS_REGION=ap-southeast-2" \
            -v "./out:/out" \
            --rm -t ghcr.io/sinatra-transport/s3-sync-utility:0.1.1 \ 
            changes -o "s3://${{ vars.AWS_PRIVATE_BUCKET }}/file-index-develop.pb" -n /out/index.pb
                